apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-v1
spec:
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: tryggth/frontend:v1
          imagePullPolicy: Always
          env:
            - name: REGION
              value: "SPACE"
          args:
            - "-bar=bar:8080"
            - "-foo=foo:8080"
            - "-grpc=0.0.0.0:8080"
            - "-health=0.0.0.0:8008"
            - "-http=0.0.0.0:80"
            - "-region=$(REGION)"
          ports:
            - name: grpc
              containerPort: 8080
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 20M
            requests:
              cpu: 100m
              memory: 10M
